### PR TITLE
 Add repos and online stars badge

### PR DESCRIPTION
**Pull request by soroushchehresa**

### CODE REVIEW

**Comment by ilius** [comment]
I think you are supposed to modify `data.json` only. `README.md` is auto-generated.

**Comment by soroushchehresa** [comment]
@ilius Thanks for the review.
I reverted all changes in the README.md.
Please check again.

**Comment by ilius** [comment]
I'm not a reviewer.
But the change in `template.md` is supposed to make each stars count a link, right?
If so, why is not working on your own fork?

**Comment by soroushchehresa** [comment]
@ilius I forgot to build the project when adding the online stars badge.
You can see the live example on my own fork now :)

**Pull request closed without merging**
