### PR TITLE
Add some C++ projects

### PR DESCRIPTION
**Pull request by alipiry**

### CODE REVIEW

**Comment by alipiry** [comment]
@mohebifar Any update?

**Comment by ilius** [comment]
I think they want each PR to add one repo only.

**Comment by alipiry** [comment]
> I think they want each PR to add one repo only.

Really don't have enough time to submit separated PR :)

**Comment by mohebifar** [comment]
@alipiry Nice projects. I couldn't merge this because you'd changed `README.md` instead of `data.json`. All changes to `README.md` will get overwritten by scheduled Travis job. Please feel free to open a new PR. You can include all these three repos in one PR as long as you just add it to `data.json`.

**Comment by alipiry** [comment]
> @alipiry Nice projects. I couldn't merge this because you'd changed `README.md` instead of `data.json`. All changes to `README.md` will get overwritten by a scheduled Travis job. Please feel free to open a new PR. You can include all these three repos in one PR as long as you just add it to `data.json`.

Oh sorry, my bad! Alright then. I'll submit new PR, tnx anyway

**Pull request closed without merging**
