### PR TITLE
Add HosseinKarami/fastshell

### PR DESCRIPTION
**Pull request by HosseinKarami**

### CODE REVIEW

**Comment by mohebifar** [comment]
Great work with that. But I suppose that's not much of JavaScript nor HTML/CSS. I don't know where to put it. Maybe we can make a new portion like "Boilerplate".

**Comment by HosseinKarami** [comment]
i agree with u, It's better to use "Boilerplate" 👍

**Comment by mohebifar** [comment]
Please rebase @HosseinKarami

**Comment by HosseinKarami** [comment]
Done

**Comment by mohebifar** [comment]
Thanks, please squash your commits.

**Comment by HosseinKarami** [comment]
👍

**Pull request closed without merging**
