### PR TITLE
i've added my proposal for tehran.js website in boilerplate category

### PR DESCRIPTION
**Pull request by hesmaili**

### CODE REVIEW

**Comment by mohebifar** [comment]
It actually is not a boilerplate. However, I merged it for the time being until finding a better category for these sort of repos.

**Comment by hesmaili** [comment]
base on definition ,i agree with you it's not a boilerplate but i saw most of items in this category are similar ,so i decided to add my item .by the way thanks mohamdad 👍👍

**Comment by mamal72** [comment]
We can create a `website` category and put all websites and webpages there.

**Comment by hesmaili** [comment]
yeah . it's good idea at least better than ``boilerplate``

**Pull request merged**
